### ISSUE TITLE
Spark 实验步骤2，单词打错了？

### ISSUE THREAD

**Issue by cdt2019** [datawhalechina/juicy-bigdata#32]
第七章. Spark
7.4.1.3 实验步骤
2.更改文件夹名和所属用户
使用mv命令，将文件名改为hive，命令如下：
sudo mv /opt/spark-3.2.0-bin-without-hadoop/ /opt/spark

hive 打错了, 应该为spark?

**Comment by shenhao-stu** [comment]
嗯嗯，感谢指正，已更改🎉
